In [2]:
import pandas as pd
import numpy as np
from dotenv import load_dotenv
import os
_ = load_dotenv()

In [ ]:
pip install python-dotenv

In [6]:
file_path = 'RAW_Data/main_data.csv'
df = pd.read_csv(file_path)
df['product_id'].value_counts()

BTC-USD     1084
ETH-USD     1084
SOL-USD     1084
ADA-USD     1084
LINK-USD    1084
LTC-USD     1084
XRP-USD      343
Name: product_id, dtype: int64

In [11]:
df['Unnamed: 0']
crypto_data = df.drop(columns = 'Unnamed: 0')
crypto_data

,time,low,high,open,close,volume,price_change,average_price,volatitlity,product_id
0,2021-12-27,50480.00,52100.00,50804.33,50717.77,11596.914682,-86.56,51290.000,3.209192,BTC-USD
1,2021-12-26,49460.00,51295.33,50428.31,50801.79,6863.394738,373.48,50377.665,3.710736,BTC-USD
2,2021-12-25,50191.84,51171.68,50852.31,50428.31,5550.571532,-424.00,50681.760,1.952190,BTC-USD
3,2021-12-24,50445.55,51878.60,50842.06,50851.38,11690.454182,9.32,51162.075,2.840786,BTC-USD
4,2021-12-23,48032.16,51397.82,48608.61,50842.20,16627.046280,2233.59,49714.990,7.007097,BTC-USD
...,...,...,...,...,...,...,...,...,...,...
6842,2024-01-02,72.50,75.94,74.75,72.98,163486.587394,-1.77,74.220,4.744828,LTC-USD
6843,2024-01-01,72.05,74.83,72.81,74.75,112009.560933,1.94,73.440,3.858432,LTC-USD
6844,2023-12-31,71.45,74.21,73.24,72.80,117693.683399,-0.44,72.830,3.862841,LTC-USD
6845,2023-12-30,72.38,73.99,73.21,73.23,175907.481069,0.02,73.185,2.224371,LTC-USD
6846,2023-12-29,72.80,77.85,76.54,73.22,315107.799974,-3.32,75.325,6.936813,LTC-USD

In [ ]:
df['time'] = pd.to_datetime(df['time'])
print(df['time'].dtype)

In [ ]:
df.head()

In [3]:
## test connection to mysql
import mysql.connector

In [14]:
mydb = mysql.connector.connect(
  host='localhost',
  user=os.getenv('USER'),
  password=os.getenv('PASSWORD')
  # host='localhost',
  # user='root',
  # password='Vikings329!vikings'
)

mycursor = mydb.cursor()
mycursor.execute("USE CAPSTONE")
mycursor.execute("SELECT * FROM HISTORIC_CRYPTO_PRICES")

# for x in mycursor:
#   print(x)

In [ ]:
pip install mysql-connector-python